### PR TITLE
update to newest cloudflare-api-client version

### PR DESCRIPTION
**Pull request by bpholt**
Co-authored-by: Brian P. Holt <bholt@dwolla.com>
Co-authored-by: Nick Leeper <nickl@dwolla.com>

@nleeper this PR contains the upgrades to the Cats-based Cloudflare client for account management from the `rate-limits` branch, but omits the rate limiting code (which AFAICT was mostly stubs so far). I plan to use this as a baseline for the domain settings features I plan to add.

If you want, I can push up a rebase of the `rate-limits` branch, so it starts from here and adds the work so far for rate limiting in a subsequent commit.

### CODE REVIEW

**Comment by bpholt** [comment]
Also, I assumed the account management work was pretty much done, modulo some refactoring, but that should be confirmed as part of this review. For example, I noticed there's no support for deleting accounts—is that intentional?

**Comment by bpholt** [comment]
Ok, I updated the PR with support for deleting records and several test cases that were implemented on master but had been accidentally deleted. I think this should be ready for review now!

**Comment by nleeper** [comment]
This looks good to me, I think you've captured all the work from account membership. Its probably a good idea for someone else to look at this also.

**Comment by bpholt** [comment]
FYI I tested this in the sandbox and was able to remove and create a Cloudflare user in two consecutive CloudFormation stack updates using the new code. I'm going to push an update to the README and then merge this.

**Pull request merged**
